---
title: "regression"
format: html
---

```{r}
#| message: false

library(tidyverse)
library(fpp3)
library(ggtime)
```

```{r}
us_change |> 
  ggplot(aes(x = Quarter)) +
  geom_line(aes(y = Consumption, colour = "Consumo")) +
  geom_line(aes(y = Income, colour = "Ingreso")) +
  ylab("cambio %") + xlab("Año") +
  guides(colour=guide_legend(title="Series")) + 
  theme(legend.position = "top")
```

```{r}
us_change |> 
  ggplot(aes(x=Income, y=Consumption)) +
    ylab("Consumo (cambio % trimestral)") +
    xlab("Ingreso (cambio % trimestral)") +
    geom_point() +
    geom_smooth(method="lm", se=FALSE)
```

```{r}
fit1 <- us_change |> 
  model(
    lm = TSLM(Consumption ~ Income)
  ) 

fit1 |> 
  report()
```
```{r}
augment(fit1) |>  
  ggplot(aes(x = Quarter)) +
  geom_line(aes(y = Consumption, color = "Datos")) +
  geom_line(aes(y = .fitted, color = "Fitted"))+
  xlab("Año") + ylab(NULL) +
  ggtitle("Cambios porcentuales en el gasto de Consumo en EEUU") +
  guides(color = guide_legend(title = NULL))
```


```{r}
augment(fit1) |>  
  ggplot(aes(x = Consumption, y = .fitted)) +
  geom_point() +
  ylab("Fitted (valores ajustados)") +
  xlab("Datos (reales históricos)") +
  ggtitle("Cambios porcentuales en el gasto de Consumo en EEUU") +
  geom_abline(intercept = 0, slope = 1)
```

```{r}
fit1 |> 
  gg_tsresiduals()
```

```{r}
#| message: false

us_change |>  
  as_tibble() |> 
  select(-Quarter) |>  
  GGally::ggpairs()
```

```{r}
fit2 <- us_change |> 
  model(
    lm2 = TSLM(Consumption ~ Income + Production + Savings + Unemployment)
  ) 

fit2 |> 
  report()
```

```{r}
augment(fit2) |>  
  ggplot(aes(x = Quarter)) +
  geom_line(aes(y = Consumption, color = "Datos")) +
  geom_line(aes(y = .fitted, color = "Fitted"))+
  xlab("Año") + ylab(NULL) +
  ggtitle("Cambios porcentuales en el gasto de Consumo en EEUU") +
  guides(color = guide_legend(title = NULL))
```

```{r}
augment(fit2) |>  
  ggplot(aes(x = Consumption, y = .fitted)) +
  geom_point() +
  ylab("Fitted (valores ajustados)") +
  xlab("Datos (reales históricos)") +
  ggtitle("Cambios porcentuales en el gasto de Consumo en EEUU") +
  geom_abline(intercept = 0, slope = 1)
```

```{r}
fit2 |> 
  gg_tsresiduals()
```

```{r}
df <- left_join(us_change, residuals(fit2), by = "Quarter")
df |> 
  select(-c(Consumption, .model)) |>  
  pivot_longer(cols = c(Income:Unemployment)) |>  
  ggplot(aes( x = value, y = .resid, color = name)) + 
  geom_point() + ylab("Residuales") + xlab("Predictoras") +
  facet_wrap(~ name, scales = "free_x") +
  theme(legend.position = "none")
```

# Pronóstico

## Train data

```{r}
us_change_train <- us_change |> 
  filter_index(. ~ "2017 Q4")

us_change_train
```

```{r}
#| message: false

us_change_train |> 
  as_tibble() |> 
  select(-Quarter) |> 
  GGally::ggpairs()
```

## Model Estimation

```{r}
us_change_fit <- us_change_train |> 
  model(
    lm = TSLM(Consumption ~ Income + Production + Savings + Unemployment)
  )

us_change_fit |> 
  report()
```

La ecuación de regresión propuesta es:

$$
y_{t,consumption} = \beta_0 + \beta_1 x_{t,income} + \beta_2 x_{t,production} + \ beta_3 x_{t,savings} + \beta_4 x_{t,unemployment} + \varepsilon_t
$$

## Pronóstico

## Ex-post

Aquí comparamos usando los datos del test.

```{r}
us_change |> filter_index("2018 Q1" ~ .)
us_change_fc_ex_post <- us_change_fit |> 
  forecast(new_data = us_change |> filter_index("2018 Q1" ~ .))

us_change_fc_ex_post |>
  autoplot(us_change|> filter_index("2010 Q1" ~ .)) +
  ylab("Cambio % en Consumo") +
  xlab("Año") +
  ggtitle("Pronóstico ex-post del cambio porcentual en el Consumo en EEUU")

us_change_fc_ex_post

us_change_fc_ex_post |> 
  accuracy(us_change)
```

## Ex-ante

Necesitamos datos de las predictoras.



```{r}
us_change

us_change_long <- us_change |> 
  pivot_longer(cols = - c(Quarter, Consumption)) 

us_change_long

us_change_long |> 
  autoplot(value) +
  facet_wrap(vars(name), scales = "free_y") + 
  theme(legend.position = "none")
```

```{r}
us_change_fc_predictors <- us_change_long |> 
  model(
    arima = ARIMA(value)
  ) |> 
  forecast(h = 6)

us_change_fc_predictors
```

Los valores de la estimación puntual tenemos que ponerlos en una nueva tabla.

```{r}
us_change_new_data <- us_change_fc_predictors |> 
  as_tsibble() |> 
  select(-c(.model, value)) |> 
  pivot_wider(names_from = name, values_from = .mean)

us_change_new_data
```

```{r}
us_change_fc_ex_ante <- us_change_fit |>
  refit(us_change) |> 
  forecast(new_data = us_change_new_data)

us_change_fc_ex_ante |>
  autoplot(us_change |> filter_index("2010 Q1" ~ .)) +
  ylab("Cambio % en Consumo") +
  xlab("Año") +
  ggtitle("Pronóstico ex-ante del cambio porcentual en el Consumo en EEUU")
```

```{r}
us_change_train_new_data <-  us_change_train |> 
  pivot_longer(cols = -c(Quarter, Consumption)) |>
  model(
    arima = ARIMA(value)
  ) |> 
  forecast(h = 6) |>
  as_tsibble() |> 
  select(-c(.model, value)) |> 
  pivot_wider(names_from = name, values_from = .mean)

us_change_fc_ex_ante_train <- us_change_fit |>
  forecast(new_data = us_change_train_new_data) |> 
  mutate(.model = "ex_ante_train")

us_change_fc_ex_ante_train

us_change_fc_ex_post_full <- us_change_fc_ex_post |> 
  full_join(us_change_fc_ex_ante_train)

us_change_fc_ex_post_full |> 
  autoplot(us_change |> filter_index("2010 Q1" ~ .), level = NULL) +
  ylab("Cambio % en Consumo") +
  xlab("Año") +
  ggtitle("Pronóstico ex-post vs ex-ante (train) del cambio porcentual en el Consumo en EEUU") +
  guides(color = guide_legend(title = "Tipo de pronóstico"))

us_change_fc_ex_post_full |>
  accuracy(us_change)
```

## Pronósticos con escenarios

```{r}
escenarios <- scenarios(
  pesimista = new_data(us_change, 6) |> 
    mutate(
      Income       = c(-1.0, -0.5, 0.0, -0.5, -1.0, -1.5),
      Production   = c(-0.5, -0.5, -0.5, -1.0, -1.0, -1.5),
      Savings      = c(0.5, 0.5, 0.0, 0.5, 0.5, 1.0),
      Unemployment = c(0.5, 0.5, 1.0, 1.0, 1.5, 2.0)
    ),
  optimista = new_data(us_change, 6) |> 
    mutate(
      Income       = c(1.0, 1.5, 2.0, 1.5, 1.0, 0.5),
      Production   = c(1.0, 1.0, 1.5, 1.5, 2.0, 2.5),
      Savings      = c(-0.5, -0.5, -1.0, -1.0, -1.5, -2.0),
      Unemployment = c(-0.5, -0.5, -1.0, -1.0, -1.5, -2.0)
    )
)

us_change_fc_scenarios <- us_change_fit |> 
  refit(us_change) |> 
  forecast(new_data = escenarios)

us_change |> 
  autoplot(Consumption) +
  autolayer(us_change_fc_scenarios, level = NULL) +
  autolayer(us_change_fc_ex_ante, level = NULL) +
  ylab("Cambio % en Consumo") +
  xlab("Año") +
  ggtitle("Pronóstico con escenarios del cambio porcentual en el Consumo en EEUU")
```

