---
title: "Descomposición"
format: html
---

```{r}
library(tidyverse)
library(fpp3)
```

Vamos a importar los datos de las medicinas:


```{r}
# ALT + "-" para agregar " <- "
medicinas <- read_csv("datos/medicinas.csv")
medicinas
```

Tenemos que convertirla a una `tsibble`. Para ello, tenemos que primero cambiar el formato de la fecha a un objeto `yearmonth`:

```{r}
medicinas <- medicinas |>
  mutate(fecha = yearmonth(fecha)) |> 
  as_tsibble(index = fecha)

medicinas
```

Graficamos la serie

```{r}
medicinas |> 
  autoplot(Cost)
```

Como habíamos visto, la serie tiene una tendencia a la alza y un fuerte patrón estacional. Hacemos la descomposición clásica, tal como la hicimos en Excel:

```{r}
#| warning: false

medicinas_dcmp <- medicinas |>
  model(dcmp_clasica = classical_decomposition(Cost, type = "multiplicative")) |>
  components()

medicinas_dcmp

medicinas_dcmp |> 
  ggplot(aes(y = Cost, x = fecha)) +
  geom_line(color = "grey") +
  geom_line(aes(y = season_adjust), color = "blue")

medicinas_dcmp |> 
  autoplot()
```

